### ISSUE TITLE
Web browser navigation of profile information

### ISSUE THREAD

**Issue by nicholascar** [w3c/dx-connegp#14]
### Use case: web browser navigation of profile information
Status: Proposed

Identifier:

Creator: Nicholas Car

Deliverable(s): Content Negotiation

## Stakeholders
data consumer

## Problem statement
For human Linked Data data consumers, it is difficult to use HTTP headers such as `Accept` to perform content negotiation. Web browsers, the primary tool humans use to access Internet resources, do not lend themselves easily to HTTP header setting for non-advanced users. 

In addition to any HTTP Content Negotitation-based approaches to navigate available profiles of information about a resource, we wish to provide a web-browser-friendly equivalent methods for humans.

### Alternates View
Established practice in Australian science agencies is to have a catalogue server that is able to respond to Query String Arguments (QSA) in place of, or even overriding, HTTP headers. 

When using the [Geoscience Australia Samples Catalogue](http://pid.geoscience.gov.au/samples/), data consumers are able to ask for different profiles of metadata about samples using a `_view` QSA and different formats either using the HTTP Accept header or a `_format` QSA which, if present, will override the Accept header. For [Sample AU239](http://pid.geoscience.gov.au/sample/AU239), some available profiles and the formats they are available in are:

Name|Token|Formats|Namespace|Description
----|----|----|----|----
PROV Ontology | prov | text/html, text/turtle, application/rdf+xml | http://www.w3.org/ns/prov/ | The W3C's provenance data model
SOSA Ontology | sosa | text/turtle, application/rdf+xml, application/rdf+json | http://www.w3.org/ns/sosa/ | The W3C's Sensor, Observation, Sample, and Actuator ontology within the Semantic Sensor Networks ontology
IGSN Schema 1 | igsn-r1 | text/xml | http://schema.igsn.org/description/1.0 | Version 1 of the official IGSN XML schema

**Current Process**:
1. user follows URI to resource, e.g. Sample AU239: <http://pid.geoscience.gov.au/sample/AU239>
2. user knows, by *alternates View* convention that appending `_view=alternates` to the URI will yield a list of the alternative view and formats for the resource, as per the table above: <http://pid.geoscience.gov.au/sample/AU239?_view=alternates>
3. user selects a *view* and a *format* to their liking or relies on defaults. The *view* is indicated by a token, the token described by a Name, Description and Namespace, as perh teh table above
4. user constructed a URI using `_view` & `_format` QSAs based on *view* token and *format* MIME type. For Sample AU239, the SOSA Ontology *view* uses token *sosa* and in *turtle* format uses MIME type *text/turtle* giving URI <http://pid.geoscience.gov.au/sample/AU239?_view=sosa&_format=text/turtle> 

The existing approach does:
* allow for human and machine-readable listings of profiles available for a resource
  * machine-readability is enabled since the conventionally-located listing of the Alternates View (using *_view=alternates*) is, itself, available in machine-readable views e.g. RDF & JSON
* some metadata for profiles to be machine accessed

This existing approach does not:

* profiled an HTTP method for profile selection, other than the `_view` QSA
* indicating which properties in a profile, if not explicitly namespaced in the profile representation, belong to which namespace
* indicating precisely Base Standard identity of a profile (a "view" in the legacy system). Ontology and schema namespace URIs are often, but not always, used
* supply specific HTTP responses to profile questions
  * default profiles are supplied when the server cannot respond to a profile request given by a _view QSA indicating a profile identifier token
* directly indicate whether a profile is 'open' or 'closed' with respect to the schema/ontology it is adhering to
  * this is left to the rules of that ontology/schema to allow/disallow
* directly indicate methods for profile validation, other than schema comparison, if the profile is defined by a schema

### OAI-PMH
The [Open Archives Initiative Protocol for Metadata Harvesting](https://www.openarchives.org/OAI/openarchivesprotocol.html) is a well established protocol for requesting XML-based metadata for resources. It allows for profile listing via a QSA command paired with a resource identifier and for profile retrieval using a `metadataPrefix` QSA. Given that all responses are in XML, OAI-PMH implements profiles but not formats.

The same system delivering GA's Samples metadata as mentioned above can deliver OAI-PMH metadata too. Some example requests for the sample AU239 mentioned above also are:

URI | Result
--|--
<http://pid.geoscience.gov.au/samples/oai?verb=ListMetadataFormats&identifier=AU239> | lists the metadata profiles available for resource with identifier AU239
<http://pid.geoscience.gov.au/samples/oai?verb=GetRecord&identifier=AU239&metadataPrefix=oai_dc> | gets the metadata for resource AU239 according to the "oai_dc" profile (described in ListMetadataFormats)
<http://pid.geoscience.gov.au/samples/oai?verb=GetRecord&identifier=AU239&metadataPrefix=igsn> | gets the metadata for resource AU239 according to the "igsn"

### Other Implementations
Another implementations of profile negotiation that are similar to OAI-PMH include the Open Geospatial Consortium's [Catalogue Service for the Web](http://www.opengeospatial.org/standards/cat) which uses only XML as the format but allows for QSA-based profile listings and selection.

## Links
Systems implementing the existing approach:
* [Geoscience Australia Samples Catalogue](http://pid.geoscience.gov.au/samples/)
* [Geocoded National Address File Linked Data](http://gnafld.net) - another implementation of the Alternates View approach

## Requirements
Provide a way, for each profile negotiation function enabled by an HTTP method, to trigger the same action in browser-friendly method 

## Related use cases
[Requirement 6.5.2 Distribution schema [RDIS]](https://www.w3.org/TR/dcat-ucr/#RDIS)
[Requirement 6.8.4 Profiles listing [RPFL]](https://www.w3.org/TR/dcat-ucr/#RPFL)
[Requirement 6.8.2 Profile representation [RPFRP]](https://www.w3.org/TR/dcat-ucr/#RPFRP)

**Comment by agreiner** [comment]
The simplest solution to this is for the publisher of the dataset to offer an html page with links to the different distributions, and human readable text summarizing the differences between them, something like the following:

The figglewood dataset is available in conformance to the following profiles:

<a href="http://example.com/figglewood/snorbert">snorbert</a> (sleep apnea research)
<a href="http://example.com/figglewood/sippit">sippit</a> (beer and wine tasting)

The sippit profile offers the same data as snorbert with the addition of taste evaluation descriptors.

**Comment by kcoyle** [comment]
IF we consider this to be in scope, perhaps we need a label for deferred features, assuming that Conneg has decided not to address this at this time.
