### ISSUE TITLE
Change shortcode to dx-connegp

### ISSUE THREAD

**Issue by nicholascar** [w3c/dx-connegp#17]
As per discussed in plenary meeting 2020-02-26, the shortcode for the *Content Negotiation by Profile* document needs to remove the PROF association therefore it should be changed from `dx-prof-conneg` to `dx-conneg`.

A corollary: is it necessary to retain the `dx-` also? could not the document just be `conneg`, i.e. `https://www.w3.org/TR/conneg/`?

**Comment by plehegar** [comment]
conneg or connegp ? we agreed last week to use dx-connegp for the repo. So I would think it's either connegp or dx-connegp for the shortname.

**Comment by nicholascar** [comment]
Typo, yes, **connegp**

**Comment by nicholascar** [comment]
Issue solved by PR #22
