### ISSUE TITLE
Specify the realisation order of precedence for conflicting profile negotiation situations

### ISSUE THREAD

**Issue by nicholascar** [w3c/dx-connegp#2]
It is clearly specified that QSA has precedence over HTTP if both are supported, however there is no proposed mechanism for specifying the relative precedence of other URL based implementations.  Can this be left to implementations to specify or must the situation be handled in this specification?

**Comment by nicholascar** [comment]
I suggest a principle and then we have to work out the details. The principle is: the more deliberately implemented realisation should win.

So, QSA over HTTP (as QSA is a fixed thing, HTTP could be auto-set by a server).

I can’t yet decide about QSA v. REST. In the REST test I’m now doing, there are more fixed ways of specifying a profile but no option for preferences, unlike HTTP & QSA. So perhaps REST over QSA.

I will add test examples here to debate.

**Comment by larsgsvensson** [comment]
Can you elaborate a bit on what you mean by REST in this case? To me QSA _is_ a REST implementation (you simply ask for a specific resource and get a representation of the current state of that resource).

**Comment by nicholascar** [comment]
Sure: there's the possibility to use RESTful resource URIs without QSAs, for example you could implement "list profiles" for `/a/resource` with `/a/resource/profile/` etc. as opposed to the QSA `/a/resource?_profile=list` and perhaps implement "get resource by profile" with /a/resource/profile/TOKEN.

So a simple pattern of `RESOURCE_URI /profile/ PROFILE_TOKEN` and perhaps `RESOURCE_URI /profile/ PROFILE_TOKEN /mediatype/ MEDIATYPE_TOKEN` if: a) MEDIATYPE_TOKENs don't generate invalid URIs and b) other conneg dimensions such as language can be catered for too, perhaps `RESOURCE_URI /profile/ PROFILE_TOKEN /mediatype/ MEDIATYPE_TOKEN /(language|lang)/ LANGUAGE_TOKEN.

The main thing to sort out with this URI-only approach is to order the /dimension/dimension_token pairs. Should it be:

`RESOURCE_URI / [PROFILE_PAIR] / [MEDIATYPE_PAIR] / [LANGUAGE_PAIR] / [X_PAIR] ...`

or perhaps another order? The order should perhaps follow processing order so that would imply:

`RESOURCE_URI / [MEDIATYPE_PAIR] / [PROFILE_PAIR] ...`

But I don't know enough about language, time (I think Memento says it's first?) etc.

Obviously this purely hierarchical approach is limited compared to HTTP & QSA as it's hard to see sensible URIs doing the equivalent to:

`?_profile=xxx&_mediatype=text/turtle,application/ld+json,application/rdf+xml`

But loads of sites use, for example, /en/ for English representations of things so I think it's sensible to cater for this.

**Comment by agreiner** [comment]
I think that you get data-prof1.csv if you request /data/prof-1.csv or /data.csv?profile=prof1 or whatever, unless the owner happened to set up content negotiation for /data/prof-1.csv or data.csv. Why anyone would set that up is beyond me, and seems such an unusual edge case that I think it should just follow the rules of currently available content negotiation. I see no reason to request a departure from that standard.

**Comment by rob-metalinkage** [comment]
Seeing no disagreement over primacy of QSA over HTTP headers, decision is ACTION-373 - Provide text for order of precedence (#505)
