### ISSUE TITLE
A typo in AltR (i.e., shouldn't `rdf:Resource` be `rdfs:Resource`)...?

### ISSUE THREAD

**Issue by pmcb55** [w3c/dx-connegp#26]
Hi, just looking that the Turtle for [AltR](https://w3c.github.io/dx-connegp/connegp/#altr-owl) for the first time, and I notice that it's referring to `rdf:Resource`. But that term doesn't exist in the RDF namespace - it exists in the RDFS namespace. Is this a typo, or are you guys deliberately attempting to define a brand new term in the RDF namespace...?

**Comment by nicholascar** [comment]
Yes, should be `rdfs:Resource`

**Comment by rob-metalinkage** [comment]
handled by PR #48
