### ISSUE TITLE
Shouldn't AltR be sub-classing existing terms from other vocbaularies?

### ISSUE THREAD

**Issue by pmcb55** [w3c/dx-connegp#27]
Referring to the Turtle/OWL for AltR [here](https://w3c.github.io/dx-connegp/connegp/#altr-owl):
Is it really best practice to be adding restrictions, or even a `skos:scopeNote` meta-data, to an already existing term from another vocabulary - specifically `rdfs:Resource` (I assume [there's a typo there now](https://github.com/w3c/dx-connegp/issues/26))? If I load this T-box data into my existing triplestore, then it'll infer that `skos:scopeNote` applies to all instances of `rdfs:Resource` I may have already in my dataset, which wouldn't be correct.

Should you not be sub-classing `rdfs:Resource` and adding your scope-specific restrictions and meta-data to that sub-classed term? E.g., something like:
```
altr:Resource
    rdfs:subClassOf rdfs:Resource ;
    a owl:Class ;
    rdfs:label "Resource" ;
    skos:definition "The class resource, everything."@en ;
    rdfs:subClassOf [
        a owl:Restriction ;
        owl:onProperty altr:hasRepresentation ;
        owl:allValuesFrom altr:Representation
    ] ;
    dct:source "http://www.w3.org/2000/01/rdf-schema#Resource" ;
    skos:scopeNote "In the context of this mode, rdf:Resource instances are
                    used to identify Internet resources, that is items
                    identified by a URI." .
```
I notice the existing issue [here](https://github.com/w3c/dx-connegp/issues/12) suggests dropping the restriction, but the same issue applies to `skos:scopeNode`.

And the issue applies to `dct:conformsTo` and `dct:Standard` too.

**Comment by rob-metalinkage** [comment]
check if latest clean ups have resolved this already

**Comment by rob-metalinkage** [comment]
Will generate PR removing what seems to be redundant description of rdfs:Resource.

**Comment by rob-metalinkage** [comment]
Agreed 07 Feb @nicholascar to remove
