### ISSUE TITLE
URIs in figure 2 could be turned into links to increase clarity

### ISSUE THREAD

**Issue by ssstolk** [w3c/dx-connegp#32]
Figure 2 of https://www.w3.org/TR/2019/WD-dx-prof-conneg-20191126/ contains URIs abbreviated using prefixes.
In order for readers not to mistake these for unprefixed URIs (e.g., <cnpr:http>), perhaps consider making these links to the full address (where I assume the functional profiles themselves will be hosted).

**Comment by rob-metalinkage** [comment]
At the top of the figure it defines the prefix binding.

**Comment by rob-metalinkage** [comment]
this is ok - but altp: is used and probably altr: is intended, which is not defined.

**Comment by nicholascar** [comment]
Nick to address this Issue with a PR:

* change all `altp` refs to `altr`
* create a namespaces table in the document preamble
