### ISSUE TITLE
Add text to clarify that profile URIs don't have to resolve

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/dx-connegp#37]
Regarding the point, that profile URIs don't necessarily have to resolve, @tombaker noted: 

> That's an interesting point. The URIs in RDF triples also do not have to resolve. Moreover, a URI in an RDF triple that resolves today may not resolve five years from now (owner moved on, DNS fee not paid, project finished...), but that does not make the triple invalid.
The same thing could happen to a profile URI, but it could continue to serve its purpose for CONNEG, so perhaps it is indeed worth pointing this out.

We should add some text to clarify this.

**Comment by YoucTagh** [comment]
The document says:

> 7.2 Profile Identification
A [client](https://w3c.github.io/dx-connegp/connegp/#dfn-client) [request](https://w3c.github.io/dx-connegp/connegp/#dfn-request)ing the representation of a [resource](https://w3c.github.io/dx-connegp/connegp/#dfn-resource) conforming to a [data profile](https://w3c.github.io/dx-connegp/connegp/#dfn-data-profile) MUST identify the [resource](https://w3c.github.io/dx-connegp/connegp/#dfn-resource) by a Uniform Resource Identifier (URI) [[RFC3986](https://w3c.github.io/dx-connegp/connegp/#bib-rfc3986)] and MUST identify the [profile](https://w3c.github.io/dx-connegp/connegp/#dfn-profile) either by a URI or a [token](https://w3c.github.io/dx-connegp/connegp/#dfn-token).

> If a URI is used for profile identification, it SHOULD be an HTTP URI that dereferences to a description of the profile. Other kinds or URIs, e. g. URNs, MAY also be used and these may not be dereferenceable. If a token is used, it MUST unambiguously identify the [data profile](https://w3c.github.io/dx-connegp/connegp/#dfn-data-profile) within a [request](https://w3c.github.io/dx-connegp/connegp/#dfn-request)/[response](https://w3c.github.io/dx-connegp/connegp/#dfn-response) pair of messages. The server MUST declare the context within which the token may be mapped to a URI.

**Comment by aisaac** [comment]
Should we really be that soft? A profile identifier that doesn't resolve flies in the face of all best practices (FAIR). I'm not saying that all profile identifiers should resolve, but maybe we could add a sentence that emphasises that the SHOULD clause is really the one that corresponds to best practices for interoperability and re-use? (and I'm biting my tongue because there should have been a definition best practices to refer to, ideally...).

**Comment by larsgsvensson** [comment]
From [RFC 2119](https://www.rfc-editor.org/rfc/rfc2119)

> SHOULD   This word, or the adjective "RECOMMENDED", mean that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course.

So SHOULD is pretty strong already. A also know of a best practice saying that when a standard says SHOULD, it should(!) also give examples for when it's OK to deviate from the recommended course. In our case that could be that the profile issuer has no access to infrastructure for publishing http URIs.
