### ISSUE TITLE
Link to editors draft is broken

### ISSUE THREAD

**Issue by samuelweiler** [w3c/dx-connegp#40]
In https://www.w3.org/TR/dx-prof-conneg

**Comment by andrea-perego** [comment]
Thanks for reporting this problem, @samuelweiler .

The DXWG deliverable on "Content negotiation by profile" has a dedicated repository:

https://github.com/w3c/dx-connegp

I'm moving this issue in that space.

**Comment by rob-metalinkage** [comment]
needs to go to https://w3c.github.io/dx-connegp/connegp/

**Comment by pchampin** [comment]
Proposed PR https://github.com/w3c/dxwg/pull/1574 to fix this

**Comment by pchampin** [comment]
PR https://github.com/w3c/dxwg/pull/1574 has been merge, which solve this issue.
