### ISSUE TITLE
Is this spec dead?

### ISSUE THREAD

**Issue by thake** [w3c/dx-connegp#41]
I'm wondering what the current status of this draft is. The last substantial update was in 2020. 

If it is still alive, are there any plans to make it an RFC?

**Comment by nicholascar** [comment]
Definitely not dead! The WG that produced it - DXWG - is about to kick off another round of updates and a move towards full W3C and perhaps IETF certification. Here's the current DXWG charter mentioning this: https://www.w3.org/2022/06/dx-wg-charter.html

Outside of that, the spec is used in a number of systems, for example the "Prez" family of Linked Data API tools, see https://github.com/rdflib/prez/

For an example of Prez online showing ConnegP, see the Australian Statistical Geographies Standard API, an example object with profile views:

* default view: https://asgs.linked.fsdf.org.au/dataset/asgsed3/collections/SA1/items/10102100710
* alternate views: https://asgs.linked.fsdf.org.au/dataset/asgsed3/collections/SA1/items/10102100710?_profile=alt

So, alive and well, but, as is the nature of these docs, continued development is episodic but an episode is kicking off right now.

**Comment by rob-metalinkage** [comment]
Proposing to close as informative only
