### ISSUE TITLE
Use formats attribute instead of format

### ISSUE THREAD

**Issue by YoucTagh** [w3c/dx-connegp#51]
Throughout the document `format` `Link` attribute is used. See examples ([EXAMPLE 4](https://w3c.github.io/dx-connegp/connegp/#eg-list-simple), [EXAMPLE 8](https://w3c.github.io/dx-connegp/connegp/#eg-link-headers), [EXAMPLE 9](https://w3c.github.io/dx-connegp/connegp/#eg-link-headers-loc), [EXAMPLE 10](https://w3c.github.io/dx-connegp/connegp/#eg-link-headers-altp), [EXAMPLE 12](https://w3c.github.io/dx-connegp/connegp/#eg-uri-token-multi), [EXAMPLE 16](https://w3c.github.io/dx-connegp/connegp/#eg-list-profiles-mediatype), [EXAMPLE 17](https://w3c.github.io/dx-connegp/connegp/#eg-html-altp), [EXAMPLE 19](https://w3c.github.io/dx-connegp/connegp/#eg-qsa-keydiscovery), [EXAMPLE 20](https://w3c.github.io/dx-connegp/connegp/#eg-qsa-keydisco-altprofiles), [EXAMPLE 24](https://w3c.github.io/dx-connegp/connegp/#eg-altr-multi)). To be consistent with the [IETF](https://datatracker.ietf.org/doc/html/draft-svensson-profiled-representations-01) proposal and [HTTP Link Hints](https://datatracker.ietf.org/doc/html/draft-nottingham-link-hint-02) the `formats` attribute is the one that should be used.

**Comment by rob-metalinkage** [comment]
closed with PR #55
