### ISSUE TITLE
Use ex:isProfileDefaultRepresentation instead of ex:isProfilesDefault

### ISSUE THREAD

**Issue by YoucTagh** [w3c/dx-connegp#52]
To be more explicit, I suggest to use `ex:isProfileDefaultRepresentation` instead of `ex:isProfilesDefault` to indicate if the representation is the default representation of that profile in [A.4.2 Extensions](https://w3c.github.io/dx-connegp/connegp/#altr-extensions).

**Comment by YoucTagh** [comment]
Alternatively, in the definition of `ex:isProfilesDefault`, specify that the ~~range~~ domain of the property is `altr:Representation`.

**Comment by nicholascar** [comment]
I think adding the domain is the best way to go - backwards compatible and stronger ontologically. I will create a PR for this.

**Comment by rob-metalinkage** [comment]
closed with #69
