### ISSUE TITLE
Question on IETF definition of Profile

### ISSUE THREAD

**Issue by aisaac** [w3c/dx-connegp#6]
This is especially for @RubenVerborgh but I'm eager to hear from others.
In https://github.com/w3c/dxwg/issues/963 
the new proposed definition for IETF profiles is:

> a profile is a description of structural and/or semantic constraints documents can conform to in addition to the syntactical interpretation provided by more generic MIME types.

And now as per [this commit](https://github.com/ProfileNegotiation/I-D-Profile-Negotiation/commit/33818075f0544193ecc9af68ea403d1813f2d37a) it is

> a profile is a description of structural and/or semantic constraints documents can conform to structural and/or semantic constraints on representations of documents in addition to the syntactical interpretation provided by more generic MIME types.

@smrgeoinfo suggested that 

> this IETF definition is that it defines 'profile' to only apply to profiles of MIME types-- certainly a narrower scope that our discussions here.

@RubenVerborgh refuted that, and I note that indeed the last bit of the definition seeks to clarify that profiles are not MIME type focused. 

However I am really struggling with the first part of the definition, which mentions "representations of documents" and "structural constraints". Does this part include or exclude the JSON-LD profiles that are different from our profiles, as we're trying to establish [here](https://github.com/w3c/dxwg/issues/976)? Can you give examples of "structural contraints that wouldn't be semantic constraints nor syntactical constraint? Maybe a reference to a definition for "structural" would help here.

**Comment by larsgsvensson** [comment]
@aisaac Has your original questions been satisfactorily answered? There is much discussion but I haven't seen a resolution...

**Comment by larsgsvensson** [comment]
@aisaac this issue is now "due for closing". Last chance to say that you're not satisfied!

**Comment by aisaac** [comment]
@larsgsvensson I would gladly tell that I am satisfied, but I suppose a bit of due diligence is in order: can you point here to the latest definitions of profiles in the IETF draft and the Conneg spec(s) that have one, please? The links above don't work anymore, and I'm not sure I have the right pointers myself.

**Comment by larsgsvensson** [comment]
The definition of "profile" in the latest IETF draft (not yet submitted to IETF) is:
> a description of structural and/or semantic constraints on representations of resources that apply in addition to the constraints inherently indicated by their MIME type: ([I-D §1.1 Terminology](https://profilenegotiation.github.io/I-D-Profile-Negotiation/I-D-Profile-Negotiation.html#name-terminology))

In the current ED from DXWG-CNEG, the definition is:
> A [specification](https://w3c.github.io/dx-connegp/connegp/#dfn-specification) that constrains, extends, combines, or provides guidance or explanation about the usage of other specifications.
If the specification profiled is a specialized type of specification, for example a data or a functional specification, the profile will be of the same sort - a data or functional profile.
This Content Negotiation by Profile specification concerns negotiation for data profiles, and specifies [functional profiles](https://w3c.github.io/dx-connegp/connegp/#functional-profiles-definition) for different ways of achieving this. In this document, most occurrences of the term "profile" refer to "data profile". ([Content Negotiation by Profile §3 Definitions.](https://w3c.github.io/dx-connegp/connegp/#definitions))
