### ISSUE TITLE
Use of text/xml vs application/xml media types 

### ISSUE THREAD

**Issue by YoucTagh** [w3c/dx-connegp#61]
In the document, the media type is sometimes `text/xml` and sometimes `application/xml`.

Both media types are correct, but in examples [19](https://w3c.github.io/dx-connegp/connegp/#eg-qsa-keydiscovery) and [20](https://w3c.github.io/dx-connegp/connegp/#eg-qsa-keydisco-altprofiles), there is a mismatch between the URI and the `Link` header parameters, for instance:

```
...
<http://example.org/resource/a?view=profile-y&format=text/xml>;
          rel="alternate";
          type="application/xml";
          formats="http://otherexample.org/profile/y"
...
```

**Comment by rob-metalinkage** [comment]
convert all text/xml to application/xml,

review implementations to make sure they are consistent between request and response at least, and preferable use application/xml.
