### ISSUE TITLE
Differentiating Functional & Data Profiling in Conneg

### ISSUE THREAD

**Issue by nicholascar** [w3c/dx-connegp#7]
Is the use of term "Functional Profile"  confusing when the document describes options for functionality related to Data Profiles ?

**Comment by larsgsvensson** [comment]
@aisaac scripsit:
> And in fact now I realize that as long as the title of the document is "content negotiation by profile" it is going to be very difficult to do a differentiation between the profiles of the "by profile" and other types of profiles. Sorry I should have spotted this in the first place, as an essential showstopper.

Does that mean that it would be resolved if we called the document "Content Negotiation by **Data** Profile"?
Although as @rob-metalinkage says: "**Content** Negotiation implies data"

**Comment by rob-metalinkage** [comment]
Closed in accepted PR
