### ISSUE TITLE
Add motivating text to the HTTP Alternate Representation Data Model

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/dx-connegp#9]
In his conneg-by-ap-to-CR vote, @riccardoAlbertoni  suggests that we add some motivating text to [§7.3.1.1 of conneg-by-ap](https://w3c.github.io/dxwg/conneg-by-ap/#http-altp)
> Section 7.2.1.1, an introduction about what is going to be described in this section and why you are presenting the definition of HTTP link would probably help to keep the reader on track.

(I assume it's section 7.3.1.1 since there is no §7.2.1.1 and we've shuffled things around a bit...)

@nicholascar, can you have a look at that?

**Comment by larsgsvensson** [comment]
@riccardoAlbertoni This issue is now "due for closing". Do you have any final remarks?

**Comment by riccardoAlbertoni** [comment]
No I do not have other remarks on this,Thanks
